# Generated by Django 5.1.1 on 2024-09-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_getsitefields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jirafield',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jirafield',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jirafield',
            name='schema_json',
            field=models.JSONField(),
        ),
    ]
