# Generated by Django 5.1.1 on 2024-09-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_jirafield_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jirafield',
            name='stable_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
