# Generated by Django 5.1.1 on 2024-09-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_alter_jirafield_stable_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jirafield',
            name='key',
        ),
        migrations.AddField(
            model_name='jirafield',
            name='field_key',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jirafield',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jirafield',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jirafield',
            name='schema_json',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jirafield',
            name='searcherKey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
